# ============================================================
# Breakout Trading Bot Configuration
# ============================================================
# 
# SUPPORTED TIMEFRAMES:
# ────────────────────────────────────────────────────────────
#   Minutes:  1m, 3m, 5m, 15m, 30m
#   Hours:    1h, 2h, 4h, 6h
#   Daily:    1d
#   Weekly:   1w
#
# CANDLE TIMING OPTIONS (NEW!):
# ────────────────────────────────────────────────────────────
#   wait_for_next_candle: Wait for next candle before trading
#     - true:  Trade on CONFIRMED completed candles
#     - false: Trade immediately (use previous candle)
#
#   startup_delay_minutes: Extra delay after candle close
#     - 0:     No delay (immediate after candle close)
#     - 5-10:  Recommended for 4H (price stabilization)
#     - 15-30: Recommended for Daily
#
# RECOMMENDED SETTINGS:
# ────────────────────────────────────────────────────────────
#   Active (1H):       wait: false, delay: 0
#   Conservative (4H): wait: true,  delay: 5-10
#   Position (1D):     wait: true,  delay: 15-30
# ============================================================

trading:
  symbol: "BTCUSD"
  product_id: 27
  order_size: 1
  max_position_size: 1      # Maximum total position size (prevents over-trading)
  check_existing_orders: true # Check for existing orders before placing new ones

schedule:
  timeframe: "4h"                      # ← CHANGE THIS: 30m, 1h, 2h, 4h, 6h, 1d
  timezone: "Asia/Kolkata"             # Indian Standard Time (IST)
  wait_for_next_candle: true           # Wait for next candle before placing orders
  startup_delay_minutes: 5             # Wait N minutes after candle close before placing orders

risk_management:
  stop_loss_points: 1000      # Distance from entry
  take_profit_points: 2000    # Distance from entry
  breakeven_trigger_points: 1000  # Move SL to entry after this profit

monitoring:
  order_check_interval: 10     # seconds
  position_check_interval: 5   # seconds

api:
  base_url: "https://api.india.delta.exchange"

logging:
  level: "INFO"
  file: "breakout_bot.log"
  

